# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: root.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
features.openapi:
  htmlTemplate: ./template/index.html
  theme:
    pagination: section
    showConsole: true
    colors:
      primary:
        main: "#32329f"
        # main: "#ff0000"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "Node.js"
      - lang: "JavaScript"
      